version: '3'
services:
    pipwatch_api:
        build: ./api
        ports:
            - "4000:8080"
    pipwatch_worker:
        build: ./worker
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
