version: '3'
services:
    pipwatch_api:
        build:
            context: ./api
            dockerfile: DockerfileTests
        command: ""
    pipwatch_worker:
        build:
            context: ./worker
            dockerfile: DockerfileTests
        command: ""
    pipwatch_ui:
        build:
            context: ./ui
            dockerfile: DockerfileTests
        command: ""
