version: "3"
services:
    pipwatch_api:
        build: ./api
        ports:
            - "8081:8081"
    pipwatch_worker:
        build: ./worker
        depends_on:
            - redis
        volumes:
            - ./.secret:/root/.ssh:ro
    pipwatch_ui:
        build: ./ui
        ports:
            - "8080:80"
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
