version: 2
jobs:
    test_api:
        working_directory: ~/pipwatch-api
        docker:
            - image: python:latest
        steps:
            - checkout
            - run:
                name: Install tox package for running tests
                command: pip install tox
            - run:
                name: Run tox tests
                working_directory: ~/pipwatch-api/api
                command: tox
    test_worker:
        working_directory: ~/pipwatch-worker
        docker:
            - image: python:latest
        steps:
            - checkout
            - run:
                name: Install tox package for running tests
                command: pip install tox
            - run:
                name: Run tox tests
                working_directory: ~/pipwatch-worker/worker
                command: tox
workflows:
    version: 2
    tests:
        jobs:
            - test_api
            - test_worker
