version: 2
jobs:
    build_api:
        working_directory: ~/pipwatch-api
        docker:
            - image: python:latest
        steps:
            - checkout
            - run:
                name: Update setuptools
                command: pip install -U setuptools
            - run:
                name: Build setup.py package
                working_directory: ~/pipwatch-api/api
                command: python setup.py sdist --formats=gztar
    test_api:
        working_directory: ~/pipwatch-api
        docker:
            - image: python:latest
        steps:
            - checkout
            - run:
                name: Install tox package for running tests
                command: pip install tox
            - run:
                name: Run tox tests
                working_directory: ~/pipwatch-api/api
                command: tox
            - store_test_results:
                path: ~/pipwatch-api/api/api-tests.xml
    build_worker:
        working_directory: ~/pipwatch-worker
        docker:
            - image: python:latest
        steps:
            - checkout
            - run:
                name: Update setuptools
                command: pip install -U setuptools
            - run:
                name: Build setup.py package
                working_directory: ~/pipwatch-worker/worker
                command: python setup.py sdist --formats=gztar
    test_worker:
        working_directory: ~/pipwatch-worker
        docker:
            - image: python:latest
        steps:
            - checkout
            - run:
                name: Install tox package for running tests
                command: pip install tox
            - run:
                name: Run tox tests
                working_directory: ~/pipwatch-worker/worker
                command: tox
            - store_test_results:
                path: ~/pipwatch-worker/worker/worker-tests.xml
workflows:
    version: 2
    tests:
        jobs:
            - build_api
            - build_worker
            - test_api:
                requires:
                    - build_api
            - test_worker:
                requires:
                    - build_worker
