version: 2
jobs:
    build_api:
        working_directory: ~/pipwatch-api
        docker:
            - image: python:latest
        steps:
            - checkout
            - run:
                name: Update setuptools
                command: pip install -U setuptools
            - run:
                name: Build setup.py package
                working_directory: ~/pipwatch-api/api
                command: python setup.py sdist --formats=gztar
    test_api:
        working_directory: ~/pipwatch-api
        docker:
            - image: python:latest
        steps:
            - checkout
            - run:
                name: Install tox package for running tests
                command: pip install tox
            - run:
                name: Run tox tests
                working_directory: ~/pipwatch-api/api
                command: tox
    build_ui:
        working_directory: ~/pipwatch-ui
        docker:
            - image: node:8-alpine
        steps:
            - checkout
            - run:
                name: Restore node modules
                working_directory: ~/pipwatch-ui/ui
                command: yarn install --non-interactive
            - run:
                name: Build angular application
                working_directory: ~/pipwatch-ui/ui
                command: ./node_modules/.bin/ng build --env=prod
    build_worker:
        working_directory: ~/pipwatch-worker
        docker:
            - image: python:latest
        steps:
            - checkout
            - run:
                name: Update setuptools
                command: pip install -U setuptools
            - run:
                name: Build setup.py package
                working_directory: ~/pipwatch-worker/worker
                command: python setup.py sdist --formats=gztar
    test_worker:
        working_directory: ~/pipwatch-worker
        docker:
            - image: python:latest
        steps:
            - checkout
            - run:
                name: Install tox package for running tests
                command: pip install tox
            - run:
                name: Run tox tests
                working_directory: ~/pipwatch-worker/worker
                command: tox
workflows:
    version: 2
    tests:
        jobs:
            - build_api
            - build_ui
            - build_worker
            - test_api:
                requires:
                    - build_api
            - test_worker:
                requires:
                    - build_worker
